### ISSUE TITLE
Problem:

### ISSUE THREAD

**Issue by NGGNewGen** [xxFlare/xAuth#11]
Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
19.11 15:55:24 [Server] INFO Parse error: syntax error, unexpected ';' in phar:///plugins/phar_xAuth-master_yjfuy7bMYqNK2Jl.phar/src/xFlare/xAuth/CommandManager.php on line 59

Can i just delete the ; in the plugin because this login plugin seems highly sophisticated and i want to use it :))

**Comment by xxFlare** [comment]
Fixed in the latest commit. :)

**Comment by NGGNewGen** [comment]
Yay! Thank you so much :D

**Comment by NGGNewGen** [comment]
I hope this works if it does then ur the best!!

**Comment by NGGNewGen** [comment]
Ok last thing i edited messages and everything but players still dont have to register

**Comment by NGGNewGen** [comment]
19.11 18:30:51 [Server] Server thread/NOTICE ArrayOutOfBoundsException: "Undefined offset: 255" (E_NOTICE) in "/phar_xAuth-master-1_jK_KO2QmaJfrtoT.phar/src/xFlare/xAuth/LoginTasks" at line 110
19.11 18:30:51 [Server] Server 
Right there

**Comment by xxFlare** [comment]
Check if the newest version fixed it?

**Comment by NGGNewGen** [comment]
Sure! :)

**Comment by ChiefArtz** [comment]
i wanna try now. if work i will love xFlare.

**Comment by NGGNewGen** [comment]
Ikr this plugin looks so sophisticated and awesome

**Comment by ChiefArtz** [comment]
is it work for you?

**Comment by NGGNewGen** [comment]
Nope
Still this error.
11 19:35:04 [Server] Server thread/NOTICE ArrayOutOfBoundsException: "Undefined offset: 14" (E_NOTICE) in "/phar_xAuth-e919e2c6b7feb8a8ee73a0d2e6f4dd55c9fb6098_7n4O5VVMHCzwbn1.phar/src/xFlare/xAuth/LoginTasks" at line 110

**Comment by NGGNewGen** [comment]
If its fine with xflare maybe i could fix some of the code or i can sure try

**Comment by ChiefArtz** [comment]
;-;

**Comment by NGGNewGen** [comment]
Imma mess around with some of the LoginTasks code and see if i can get it workin

**Comment by NGGNewGen** [comment]
@Xflare hey try replacing the } on 110

**Comment by NGGNewGen** [comment]
Oops i ment @xxflare

**Comment by xxFlare** [comment]
@NGGNewGen @ChiefArtz I'll do some tests to get it working by tomorrow, it's pretty late here!

**Comment by ChiefArtz** [comment]
um ok

**Comment by NGGNewGen** [comment]
Ok man hope everything works and hope u the best!

**Comment by ChiefArtz** [comment]
same guud luck

**Comment by NGGNewGen** [comment]
Error on line 116

**Comment by xxFlare** [comment]
@NGGNewGen @ChiefArtz Fixed all errors, enjoy!

Note: Ip auth could be broken,

**Comment by NGGNewGen** [comment]
REALLY URMAHGURD:D TIME TO TRY IT RN THANKS YOUUU

**Comment by NGGNewGen** [comment]
DUDE IT WORKS YOUR THE FREAKIN BEST :)

**Comment by xxFlare** [comment]
@NGGNewGen Nice! Any errors/suggestions?

**Comment by NGGNewGen** [comment]
Hmmm ill think of some suggestions thank you so much for getting this to work im sorry it was a pain cx

**Comment by ChiefArtz** [comment]
cool

**Comment by ChiefArtz** [comment]
flare u should add more join message...

**Comment by xxFlare** [comment]
@ChiefArtz Just add line breaks into the config.

"Welcome to my server\nThis is another line!"

**Comment by ChiefArtz** [comment]
omg thankyou ur genius, btw is work i luv it!

**Comment by xxFlare** [comment]
@ChiefArtz Read the smalls tip I put next time. ;p
https://github.com/xxFlare/xAuth/blob/master/resources/config.yml#L100
